version: "3"

services:
  production:
    build:
      context: .
      args:
        image: ruby:$version
        packages: ${packages_production}
        commands: ${commands_production}
        image_env: production
    image: darroue/ruby:${version}-production
    depends_on:
      - development

  development:
    build:
      context: .
      args:
        image: ruby:$version
        packages: ${packages_development}
        commands: ${commands_development}
        image_env: development
    image: darroue/ruby:${version}-development
